language: python
python:
  - "3.8"
install:
  - pip install -r test_requirements.txt
before-script:
  - pip install --upgrade orator
  - cd recipe
  - sudo chmod +x travis_test
script:
  - ./travis_test
